/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "brand-blue": "#254edb",
        "on-error-container": "#93000a",
        "background": "#f8f9ff",
        "surface-container-high": "#dce9ff",
        "tertiary-fixed-dim": "#ffb690",
        "surface-variant": "#d3e4fe",
        "outline-variant": "#c4c5d7",
        "on-secondary-fixed": "#171c25",
        "error-container": "#ffdad6",
        "surface-container": "#e5eeff",
        "on-background": "#0b1c30",
        "primary-fixed": "#dde1ff",
        "on-primary-container": "#ced4ff",
        "inverse-primary": "#b8c4ff",
        "surface-container-highest": "#d3e4fe",
        "surface-dim": "#cbdbf5",
        "on-tertiary-fixed": "#341100",
        "inverse-on-surface": "#eaf1ff",
        "tertiary-fixed": "#ffdbca",
        "primary-container": "#254edb",
        "error": "#ba1a1a",
        "secondary-container": "#dee2ef",
        "on-primary": "#ffffff",
        "secondary-fixed": "#dee2ef",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "outline": "#747686",
        "inverse-surface": "#213145",
        "surface-tint": "#274fdc",
        "surface-container-low": "#eff4ff",
        "primary-fixed-dim": "#b8c4ff",
        "on-secondary-container": "#60646f",
        "on-error": "#ffffff",
        "tertiary-container": "#9b4200",
        "secondary": "#5a5e69",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#0b1c30",
        "on-secondary-fixed-variant": "#424751",
        "on-primary-fixed-variant": "#0036bc",
        "secondary-fixed-dim": "#c2c6d3",
        "tertiary": "#763000",
        "on-tertiary-fixed-variant": "#783200",
        "on-tertiary-container": "#ffcbb2",
        "on-primary-fixed": "#001355",
        "on-surface-variant": "#444655",
        "surface-bright": "#f8f9ff",
        "surface": "#f8f9ff",
        "primary": "#0035b9",
        "figma-header": "#F8F8F8",
        "figma-blue": "#1C40CA",
        "figma-logo": "#4585C5",
        "figma-icon": "#5D6871",
        "figma-text-secondary": "#868E94",
        "figma-article-id": "#35424D"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
        "custom": "4px"
      },
      fontFamily: {
        "sans": ["Source Sans Pro", "Work Sans", "sans-serif"],
        "inter": ["Inter", "sans-serif"],
        "serif": ["Merriweather", "serif"],
        "bodoni": ["Bodoni Moda", "serif"],
        "source": ["Source Sans Pro", "sans-serif"]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
